# Exchange API Configuration
exchanges:
  binance:
    api_key: "your_binance_api_key"
    api_secret: "your_binance_api_secret"
    testnet: false  # Set to true for testing
    rate_limits:
      weight_per_minute: 1200
      orders_per_second: 10
  
  hyperliquid:
    api_key: "your_hyperliquid_api_key"
    api_secret: "your_hyperliquid_api_secret"
    testnet: false
    rate_limits:
      requests_per_minute: 60

# Trading Parameters
trading:
  min_funding_rate_diff: 0.10  # 10% annualized
  position_size: 1000  # Base position size in USD
  max_leverage: 5
  stop_loss_percentage: 0.02  # 2%
  take_profit_percentage: 0.05  # 5%
  max_slippage: 0.001  # 0.1%
  min_volume_24h: 1000000  # Minimum 24h volume in USD
  funding_rate_update_interval: 60  # seconds

# Trading Pairs
pairs:
  - BTC-USDT
  - ETH-USDT
  - SOL-USDT

# Data Collection
data:
  historical_days: 30  # Number of days of historical data to fetch
  update_interval: 300  # Update interval in seconds
  storage_path: "data/historical"
  backup_path: "data/backup"
  max_retries: 3
  retry_delay: 5  # seconds

# Analysis
analysis:
  min_data_points: 100
  correlation_window: 24  # hours
  volatility_window: 24  # hours
  funding_rate_threshold: 0.01  # 1%

# Logging
logging:
  level: INFO
  file: "logs/trading.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console_output: true

# Notifications
notifications:
  enabled: true
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: "your_email@gmail.com"
    recipient_email: "your_email@gmail.com"
  telegram:
    bot_token: "your_telegram_bot_token"
    chat_id: "your_chat_id" 